import Head from 'next/head'
import Atributies from '../component/atributies/Atributies'
import Currency from '../component/currency-list/Currency'
import Footer from '../component/footer/Footer'
import Friends from '../component/friends/Friends'
import { Navbar } from '../component/navbar/Navbar'
import QuickAccess from '../component/qiuick-access/QuickAccess'
import Questions from '../component/questions/Questions'
import Infoteher from '../component/infoTether/index'
import ChartExchangeTether from '../component/chartExchangeTether/index'
import TextInfo from '../component/textInfo/index'
import FAQ from '../component/FAQ/index'
import RegisterOffCode from '../component/registerOffCode/index'
import FormTabPrice from '../component/buySell/index'
import { Box } from '@mui/system'

// const DynamicComponentWithNoSSR = dynamic(() => import('../component/chartPrice/ChartPrice'), {
//   ssr: false
// })
export default function Home() {
  return (
    <>

      <main>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Navbar />

        {/* <DynamicComponentWithNoSSR/> */}
        <Infoteher />
        <div className='container'>
          <ChartExchangeTether />
        </div>
        <TextInfo />
        <Atributies />
        <FAQ />
        <RegisterOffCode />
        <Friends />
        <Footer />
      </main>
    </>
  )
}
